CREATE TABLE `cc_certification_engagements` (
  `id` int NOT NULL AUTO_INCREMENT,
  `employee_id` int NOT NULL,
  `engagement_type` enum('Part-time','OJT/Training') NOT NULL,
  `title` varchar(150) NOT NULL,
  `organization` varchar(150) DEFAULT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `status` enum('Pending','Ongoing','For Review','Approved','Completed','Archived') NOT NULL DEFAULT 'Pending',
  `outcome` enum('Continue','Regularize','End Engagement','Not Applicable') NOT NULL DEFAULT 'Not Applicable',
  `approved_by` int DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `certificate_generated_at` datetime DEFAULT NULL,
  `archived_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_employee_id` (`employee_id`),
  KEY `idx_status` (`status`),
  CONSTRAINT `fk_cc_certification_engagements_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `cc_event_templates` (
  `template_id` int NOT NULL AUTO_INCREMENT,
  `template_name` varchar(100) NOT NULL,
  `event_type` enum('Academic','Meeting','Seminar','Institutional Event','Cultural Event','Sports Event','Orientation','Other') NOT NULL,
  `default_title` varchar(255) NOT NULL,
  `default_description` text,
  `default_location` varchar(255) DEFAULT NULL,
  `default_target_audience` varchar(100) DEFAULT NULL,
  `default_status` enum('upcoming','ongoing','completed','cancelled') DEFAULT 'upcoming',
  `priority` enum('Normal','High','Urgent') DEFAULT 'Normal',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`template_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `cc_events` (
  `event_id` int NOT NULL AUTO_INCREMENT,
  `template_id` int DEFAULT NULL,
  `event_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `event_type` enum('Academic','Meeting','Seminar','Institutional Event','Cultural Event','Sports Event','Orientation','Other') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `event_date` date NOT NULL,
  `start_time` time NOT NULL,
  `end_time` time NOT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `location` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `target_audience` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'All Students',
  `status` enum('upcoming','ongoing','completed','cancelled') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'upcoming',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`event_id`),
  KEY `fk_event_template` (`template_id`),
  CONSTRAINT `fk_event_template` FOREIGN KEY (`template_id`) REFERENCES `cc_event_templates` (`template_id`)
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

CREATE TABLE `cc_exam_proctor` (
  `id` int NOT NULL AUTO_INCREMENT,
  `exam_schedule_id` int NOT NULL,
  `faculty_id` int NOT NULL,
  `role` enum('Lead Proctor','Proctor','Reliever') DEFAULT 'Proctor',
  `status` enum('Assigned','Confirmed','Completed','Cancelled') DEFAULT 'Assigned',
  `assigned_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_exam_proctor` (`exam_schedule_id`,`faculty_id`),
  KEY `idx_exam_schedule` (`exam_schedule_id`),
  KEY `idx_faculty` (`faculty_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `cc_exam_schedule` (
  `id` int NOT NULL AUTO_INCREMENT,
  `exam_id` int NOT NULL,
  `schedule_type` enum('Exam','Break Time') NOT NULL DEFAULT 'Exam',
  `subject_id` int DEFAULT NULL,
  `section_id` int DEFAULT NULL,
  `room_id` int DEFAULT NULL,
  `exam_date` date NOT NULL,
  `start_time` time NOT NULL,
  `end_time` time NOT NULL,
  `status` enum('Scheduled','Ongoing','Completed','Cancelled') DEFAULT 'Scheduled',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_exam` (`exam_id`),
  KEY `idx_subject` (`subject_id`),
  KEY `idx_section` (`section_id`),
  KEY `idx_room` (`room_id`),
  KEY `idx_exam_date` (`exam_date`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `cc_exams` (
  `id` int NOT NULL AUTO_INCREMENT,
  `exam_name` varchar(100) NOT NULL,
  `exam_type` enum('Preliminary','Midterm','Final','Special') NOT NULL,
  `school_year_id` int NOT NULL,
  `semester_id` int NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `status` enum('Draft','Scheduled','Ongoing','Completed','Cancelled') DEFAULT 'Draft',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_exam_sy` (`school_year_id`),
  KEY `idx_exam_sem` (`semester_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `cc_faculty` (
  `id` int NOT NULL AUTO_INCREMENT,
  `employee_id` int DEFAULT NULL,
  `faculty_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `first_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `middle_name` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `last_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `email` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `department` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `max_load` int NOT NULL DEFAULT '15',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_cc_faculty_employee` (`employee_id`),
  CONSTRAINT `fk_cc_faculty_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

CREATE TABLE `cc_faculty_load` (
  `id` int NOT NULL AUTO_INCREMENT,
  `faculty_id` int NOT NULL,
  `section_id` int NOT NULL,
  `subject_id` int NOT NULL,
  `school_year_id` int DEFAULT NULL,
  `semester_id` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_section_subject` (`section_id`,`subject_id`),
  UNIQUE KEY `uq_faculty_load` (`section_id`,`subject_id`,`school_year_id`,`semester_id`),
  KEY `idx_faculty` (`faculty_id`),
  KEY `idx_section` (`section_id`),
  KEY `idx_subject` (`subject_id`),
  KEY `idx_school_year` (`school_year_id`),
  KEY `idx_semester` (`semester_id`),
  CONSTRAINT `fk_faculty` FOREIGN KEY (`faculty_id`) REFERENCES `cc_faculty` (`id`),
  CONSTRAINT `fk_faculty_load_school_year` FOREIGN KEY (`school_year_id`) REFERENCES `rgr_school_years` (`id`),
  CONSTRAINT `fk_faculty_load_semester` FOREIGN KEY (`semester_id`) REFERENCES `rgr_semesters` (`id`),
  CONSTRAINT `fk_section` FOREIGN KEY (`section_id`) REFERENCES `cc_sections` (`id`),
  CONSTRAINT `fk_subject` FOREIGN KEY (`subject_id`) REFERENCES `rgr_subjects` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `cc_faculty_load_summary` (
  `id` int NOT NULL AUTO_INCREMENT,
  `faculty_id` int NOT NULL,
  `school_year_id` int NOT NULL,
  `semester_id` int NOT NULL,
  `total_units` int NOT NULL DEFAULT '0',
  `max_load` int NOT NULL,
  `load_status` enum('Underloaded','Normal Load','Overloaded') COLLATE utf8mb4_general_ci NOT NULL,
  `computed_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_faculty_period` (`faculty_id`,`school_year_id`,`semester_id`),
  KEY `idx_faculty` (`faculty_id`),
  KEY `idx_school_year` (`school_year_id`),
  KEY `idx_semester` (`semester_id`),
  CONSTRAINT `fk_summary_faculty` FOREIGN KEY (`faculty_id`) REFERENCES `cc_faculty` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_summary_school_year` FOREIGN KEY (`school_year_id`) REFERENCES `rgr_school_years` (`id`),
  CONSTRAINT `fk_summary_semester` FOREIGN KEY (`semester_id`) REFERENCES `rgr_semesters` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

CREATE TABLE `cc_room` (
  `id` int NOT NULL AUTO_INCREMENT,
  `room_code` varchar(20) NOT NULL,
  `room_name` varchar(100) NOT NULL,
  `building` varchar(100) DEFAULT 'Main Building',
  `floor` enum('1st Floor','2nd Floor','3rd Floor','4th Floor') NOT NULL,
  `room_type` enum('Lecture Room','Computer Laboratory','Science Laboratory','Library','Office','AVR','Court Room','Other') NOT NULL,
  `capacity` int DEFAULT '40',
  `status` enum('Available','Maintenance','Unavailable') DEFAULT 'Available',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `room_code` (`room_code`)
) ENGINE=InnoDB AUTO_INCREMENT=56 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `cc_schedule` (
  `id` int NOT NULL AUTO_INCREMENT,
  `faculty_load_id` int DEFAULT NULL,
  `room_id` int DEFAULT NULL,
  `schedule_type` enum('Class','Break Time') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'Class',
  `start_time` time DEFAULT NULL,
  `end_time` time DEFAULT NULL,
  `status` enum('Scheduled','Completed','Cancelled') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'Scheduled',
  `day_of_week` enum('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `section_id` int DEFAULT NULL,
  `faculty_id` int NOT NULL,
  `subject_id` int DEFAULT NULL,
  `school_year_id` int NOT NULL,
  `semester_id` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_faculty_schedule` (`faculty_id`,`day_of_week`,`start_time`,`end_time`,`semester_id`,`school_year_id`),
  UNIQUE KEY `uk_section_schedule` (`section_id`,`day_of_week`,`start_time`,`end_time`,`semester_id`,`school_year_id`),
  UNIQUE KEY `uk_room_schedule` (`room_id`,`day_of_week`,`start_time`,`end_time`,`semester_id`,`school_year_id`),
  KEY `fk_schedule_load` (`faculty_load_id`),
  KEY `fk_schedule_subject` (`subject_id`),
  KEY `fk_schedule_sy` (`school_year_id`),
  KEY `fk_schedule_sem` (`semester_id`),
  CONSTRAINT `fk_schedule_faculty` FOREIGN KEY (`faculty_id`) REFERENCES `cc_faculty` (`id`),
  CONSTRAINT `fk_schedule_load` FOREIGN KEY (`faculty_load_id`) REFERENCES `cc_faculty_load` (`id`),
  CONSTRAINT `fk_schedule_room` FOREIGN KEY (`room_id`) REFERENCES `cc_room` (`id`),
  CONSTRAINT `fk_schedule_section` FOREIGN KEY (`section_id`) REFERENCES `cc_sections` (`id`),
  CONSTRAINT `fk_schedule_sem` FOREIGN KEY (`semester_id`) REFERENCES `rgr_semesters` (`id`),
  CONSTRAINT `fk_schedule_subject` FOREIGN KEY (`subject_id`) REFERENCES `rgr_subjects` (`id`),
  CONSTRAINT `fk_schedule_sy` FOREIGN KEY (`school_year_id`) REFERENCES `rgr_school_years` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

CREATE TABLE `cc_section_faculty` (
  `id` int NOT NULL AUTO_INCREMENT,
  `section_id` int NOT NULL,
  `faculty_id` int NOT NULL,
  `role` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `school_year_id` int NOT NULL,
  `semester_id` int NOT NULL,
  `status` enum('Active','Completed','Reassigned','Cancelled') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'Active',
  `assigned_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ended_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_section_faculty_role` (`section_id`,`faculty_id`,`role`,`school_year_id`,`semester_id`),
  KEY `fk_sectionfaculty_sy` (`school_year_id`),
  KEY `fk_sectionfaculty_sem` (`semester_id`),
  KEY `fk_sectionfaculty_faculty` (`faculty_id`),
  CONSTRAINT `fk_sectionfaculty_faculty` FOREIGN KEY (`faculty_id`) REFERENCES `cc_faculty` (`id`),
  CONSTRAINT `fk_sectionfaculty_section` FOREIGN KEY (`section_id`) REFERENCES `cc_sections` (`id`),
  CONSTRAINT `fk_sectionfaculty_sem` FOREIGN KEY (`semester_id`) REFERENCES `rgr_semesters` (`id`),
  CONSTRAINT `fk_sectionfaculty_sy` FOREIGN KEY (`school_year_id`) REFERENCES `rgr_school_years` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

CREATE TABLE `cc_sections` (
  `id` int NOT NULL AUTO_INCREMENT,
  `section_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `grade_level` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `program_id` int DEFAULT NULL,
  `school_year_id` int DEFAULT NULL,
  `semester_id` int DEFAULT NULL,
  `adviser_id` int DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_section` (`section_code`,`school_year_id`,`semester_id`),
  KEY `fk_section_program` (`program_id`),
  CONSTRAINT `fk_section_program` FOREIGN KEY (`program_id`) REFERENCES `rgr_courses` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

CREATE TABLE `em_documents` (
  `document_id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `document_name` varchar(100) NOT NULL,
  `document_type` varchar(50) NOT NULL,
  `file_path` varchar(255) NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `file_size` varchar(50) DEFAULT NULL,
  `uploaded_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `mime_type` varchar(100) DEFAULT NULL,
  `category` varchar(100) DEFAULT 'Other',
  `expiry_date` date DEFAULT NULL,
  `verification_status` enum('Pending','Verified','Rejected','Expired') NOT NULL DEFAULT 'Pending',
  `verified_by` int(11) DEFAULT NULL,
  `verified_at` datetime DEFAULT NULL,
  `verification_notes` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `em_documents` (`document_id`, `employee_id`, `document_name`, `document_type`, `file_path`, `file_name`, `file_size`, `uploaded_by`, `created_at`, `updated_at`, `mime_type`, `category`, `expiry_date`, `verification_status`, `verified_by`, `verified_at`, `verification_notes`) VALUES
(2001, 1, 'NBI Clearance', 'NBI Clearance', 'uploads/employee_documents/1/nbi_clearance.pdf', 'NBI_Clearance_Juan_Dela_Cruz.pdf', '185432', 1, '2025-07-09 17:00:00', '2025-07-09 17:30:00', 'application/pdf', 'Government Documents', '2026-07-15', 'Verified', 1, '2025-07-10 09:30:00', 'Document already expired. Renewal required.'),
(2002, 2, 'Medical Certificate', 'Medical Certificate', 'uploads/employee_documents/2/medical_certificate.pdf', 'Medical_Certificate_Maria_Santos.pdf', '164321', 1, '2025-08-14 18:00:00', '2025-08-14 18:30:00', 'application/pdf', 'Medical Records', '2026-08-01', 'Verified', 1, '2025-08-15 10:30:00', 'Medical certificate expired. Employee should submit updated certificate.'),
(2003, 3, 'First Aid Certificate', 'Training Certificate', 'uploads/employee_documents/3/first_aid_certificate.pdf', 'First_Aid_Certificate_Ana_Reyes.pdf', '198765', 1, '2025-08-19 19:00:00', '2025-08-19 19:30:00', 'application/pdf', 'Training & Certification', '2026-08-10', 'Verified', 1, '2025-08-20 11:30:00', 'Certificate has expired.'),
(2004, 4, 'Safety Training Certificate', 'Training Certificate', 'uploads/employee_documents/4/safety_training.pdf', 'Safety_Training_Carlos_Cruz.pdf', '176543', 1, '2025-08-31 17:30:00', '2025-08-31 18:00:00', 'application/pdf', 'Training & Certification', '2026-08-15', 'Verified', 1, '2025-09-01 10:00:00', 'Required safety training certificate has expired.'),
(2005, 5, 'TESDA Certification', 'Certification', 'uploads/employee_documents/5/tesda_certificate.pdf', 'TESDA_Certification_Sofia_Garcia.pdf', '213456', 1, '2025-09-09 21:00:00', '2025-09-09 21:30:00', 'application/pdf', 'License & Certification', '2026-08-18', 'Verified', 1, '2025-09-10 13:30:00', 'Certification expired and requires renewal.'),
(2006, 6, 'PRC Professional License', 'Professional License', 'uploads/employee_documents/6/prc_license.pdf', 'PRC_License_Michael_Torres.pdf', '245678', 1, '2026-01-14 17:00:00', '2026-01-14 17:30:00', 'application/pdf', 'License & Certification', '2026-08-28', 'Verified', 1, '2026-01-15 09:30:00', 'PRC license expires in less than one week.'),
(2007, 7, 'NBI Clearance', 'NBI Clearance', 'uploads/employee_documents/7/nbi_clearance.pdf', 'NBI_Clearance_Liza_Mendoza.pdf', '187654', 1, '2026-01-31 18:00:00', '2026-08-24 09:16:28', 'application/pdf', 'Government Documents', '2026-08-30', 'Pending', NULL, NULL, 'Document uploaded and awaiting HR verification.'),
(2008, 8, 'Medical Certificate', 'Medical Certificate', 'uploads/employee_documents/8/medical_certificate.pdf', 'Medical_Certificate_Roberto_Lim.pdf', '154321', 1, '2026-02-28 19:00:00', '2026-02-28 19:30:00', 'application/pdf', 'Medical Records', '2026-09-01', 'Verified', 1, '2026-03-01 11:30:00', 'Medical certificate expires within one week.'),
(2009, 9, 'PRC Professional License', 'Professional License', 'uploads/employee_documents/9/prc_license.pdf', 'PRC_License_Jasmine_Flores.pdf', '267890', 1, '2026-01-19 17:00:00', '2026-01-19 17:30:00', 'application/pdf', 'License & Certification', '2026-09-05', 'Verified', 1, '2026-01-20 09:30:00', 'Professional license nearing expiration.'),
(2010, 10, 'Safety Training Certificate', 'Training Certificate', 'uploads/employee_documents/10/safety_training.pdf', 'Safety_Training_Daniel_Ramos.pdf', '176543', 1, '2026-02-09 21:00:00', '2026-02-09 21:30:00', 'application/pdf', 'Training & Certification', '2026-09-08', 'Verified', 1, '2026-02-10 13:30:00', 'Safety training certification expires soon.'),
(2011, 11, 'NBI Clearance', 'NBI Clearance', 'uploads/employee_documents/11/nbi_clearance.pdf', 'NBI_Clearance_Angelica_Perez.pdf', '192345', 1, '2026-02-14 22:00:00', '2026-08-24 09:16:28', 'application/pdf', 'Government Documents', '2026-09-10', 'Pending', NULL, NULL, 'Document uploaded and awaiting HR verification.'),
(2012, 12, 'PRC Professional License', 'Professional License', 'uploads/employee_documents/12/prc_license.pdf', 'PRC_License_Kevin_Navarro.pdf', '256789', 1, '2026-02-19 17:00:00', '2026-02-19 17:30:00', 'application/pdf', 'License & Certification', '2026-09-12', 'Verified', 1, '2026-02-20 09:30:00', 'PRC license expires within 30 days.'),
(2013, 13, 'Medical Certificate', 'Medical Certificate', 'uploads/employee_documents/13/medical_certificate.pdf', 'Medical_Certificate_Cristina_Velasco.pdf', '167890', 1, '2026-02-28 18:00:00', '2026-02-28 18:30:00', 'application/pdf', 'Medical Records', '2026-09-15', 'Verified', 1, '2026-03-01 10:30:00', 'Medical certificate nearing expiration.'),
(2014, 14, 'First Aid Certificate', 'Training Certificate', 'uploads/employee_documents/14/first_aid_certificate.pdf', 'First_Aid_Certificate_Paolo_Santos.pdf', '178654', 1, '2026-03-04 19:00:00', '2026-08-24 09:16:28', 'application/pdf', 'Training & Certification', '2026-09-18', 'Pending', NULL, NULL, 'Document uploaded and awaiting HR verification.'),
(2015, 15, 'TESDA Certificate', 'Certification', 'uploads/employee_documents/15/tesda_certificate.pdf', 'TESDA_Certificate_Rachel_Gomez.pdf', '201234', 1, '2026-03-09 21:00:00', '2026-03-09 21:30:00', 'application/pdf', 'License & Certification', '2026-09-20', 'Verified', 1, '2026-03-10 13:30:00', 'TESDA certification expires soon.'),
(2016, 16, 'NBI Clearance', 'NBI Clearance', 'uploads/employee_documents/16/nbi_clearance.pdf', 'NBI_Clearance_Mark_Dela_Pena.pdf', '189765', 1, '2026-03-14 17:00:00', '2026-03-14 17:30:00', 'application/pdf', 'Government Documents', '2026-09-22', 'Verified', 1, '2026-03-15 09:30:00', 'NBI clearance nearing expiration.'),
(2017, 17, 'Medical Certificate', 'Medical Certificate', 'uploads/employee_documents/17/medical_certificate.pdf', 'Medical_Certificate_Jenny_Lim.pdf', '154876', 1, '2026-03-19 18:00:00', '2026-08-24 09:16:28', 'application/pdf', 'Medical Records', '2026-09-25', 'Pending', NULL, NULL, 'Document uploaded and awaiting HR verification.'),
(2018, 18, 'PRC Professional License', 'Professional License', 'uploads/employee_documents/18/prc_license.pdf', 'PRC_License_Anthony_Rivera.pdf', '278654', 1, '2026-03-24 22:00:00', '2026-03-24 22:30:00', 'application/pdf', 'License & Certification', '2026-09-28', 'Verified', 1, '2026-03-25 14:30:00', 'PRC license nearing expiration.'),
(2019, 19, 'Safety Training Certificate', 'Training Certificate', 'uploads/employee_documents/19/safety_training.pdf', 'Safety_Training_Monica_Castillo.pdf', '183456', 1, '2026-03-31 17:00:00', '2026-03-31 17:30:00', 'application/pdf', 'Training & Certification', '2026-10-02', 'Verified', 1, '2026-04-01 09:30:00', 'Safety training certification approaching expiration.'),
(2020, 20, 'NBI Clearance', 'NBI Clearance', 'uploads/employee_documents/20/nbi_clearance.pdf', 'NBI_Clearance_Joseph_Tan.pdf', '176543', 1, '2026-04-04 18:00:00', '2026-08-24 09:16:28', 'application/pdf', 'Government Documents', '2026-10-05', 'Pending', NULL, NULL, 'Document uploaded and awaiting HR verification.'),
(2021, 21, 'PRC Professional License', 'Professional License', 'uploads/employee_documents/21/prc_license.pdf', 'PRC_License_Karen_Dizon.pdf', '245987', 1, '2026-04-09 19:00:00', '2026-04-09 19:30:00', 'application/pdf', 'License & Certification', '2026-10-10', 'Verified', 1, '2026-04-10 11:30:00', 'Professional license requires monitoring.'),
(2022, 22, 'Medical Certificate', 'Medical Certificate', 'uploads/employee_documents/22/medical_certificate.pdf', 'Medical_Certificate_Ryan_Bautista.pdf', '163245', 1, '2026-04-14 21:00:00', '2026-04-14 21:30:00', 'application/pdf', 'Medical Records', '2026-10-12', 'Verified', 1, '2026-04-15 13:30:00', 'Medical certificate approaching expiration.'),
(2023, 23, 'First Aid Certificate', 'Training Certificate', 'uploads/employee_documents/23/first_aid_certificate.pdf', 'First_Aid_Certificate_Beatrice_Cruz.pdf', '187654', 1, '2026-04-19 17:00:00', '2026-08-24 09:16:28', 'application/pdf', 'Training & Certification', '2026-10-15', 'Pending', NULL, NULL, 'Document uploaded and awaiting HR verification.'),
(2024, 24, 'TESDA Certification', 'Certification', 'uploads/employee_documents/24/tesda_certificate.pdf', 'TESDA_Certificate_Eric_Mendoza.pdf', '204567', 1, '2026-04-24 18:00:00', '2026-04-24 18:30:00', 'application/pdf', 'License & Certification', '2026-10-18', 'Verified', 1, '2026-04-25 10:30:00', 'TESDA certification approaching expiration.'),
(2025, 25, 'NBI Clearance', 'NBI Clearance', 'uploads/employee_documents/25/nbi_clearance.pdf', 'NBI_Clearance_Sheryl_Reyes.pdf', '189876', 1, '2026-04-30 19:00:00', '2026-04-30 19:30:00', 'application/pdf', 'Government Documents', '2026-10-20', 'Verified', 1, '2026-05-01 11:30:00', 'NBI clearance will expire within 60 days.'),
(2026, 26, 'PRC Professional License', 'Professional License', 'uploads/employee_documents/26/prc_license.pdf', 'PRC_License_Christian_Garcia.pdf', '265432', 1, '2026-05-04 21:00:00', '2026-08-25 02:11:14', 'application/pdf', 'License & Certification', '2026-10-25', 'Verified', NULL, '2026-08-25 18:11:14', 'Document uploaded and awaiting HR verification.'),
(2027, 27, 'Medical Certificate', 'Medical Certificate', 'uploads/employee_documents/27/medical_certificate.pdf', 'Medical_Certificate_Patricia_Lopez.pdf', '156789', 1, '2026-05-09 17:00:00', '2026-05-09 17:30:00', 'application/pdf', 'Medical Records', '2026-11-01', 'Verified', 1, '2026-05-10 09:30:00', 'Medical certificate approaching renewal period.'),
(2028, 28, 'Safety Training Certificate', 'Training Certificate', 'uploads/employee_documents/28/safety_training.pdf', 'Safety_Training_Gerald_Ong.pdf', '176890', 1, '2026-05-14 18:00:00', '2026-05-14 18:30:00', 'application/pdf', 'Training & Certification', '2026-11-05', 'Verified', 1, '2026-05-15 10:30:00', 'Safety certification will require renewal.'),
(2029, 29, 'PRC Professional License', 'Professional License', 'uploads/employee_documents/29/prc_license.pdf', 'PRC_License_Nicole_Fernandez.pdf', '254321', 1, '2026-05-19 19:00:00', '2026-08-24 09:24:58', 'application/pdf', 'License & Certification', '2026-11-10', 'Verified', NULL, '2026-08-25 01:24:58', 'Document uploaded and awaiting HR verification.'),
(2030, 30, 'NBI Clearance', 'NBI Clearance', 'uploads/employee_documents/30/nbi_clearance.pdf', 'NBI_Clearance_Adrian_Sy.pdf', '198765', 1, '2026-05-24 21:00:00', '2026-05-24 21:30:00', 'application/pdf', 'Government Documents', '2026-11-15', 'Verified', 1, '2026-05-25 13:30:00', 'NBI clearance will expire within 90 days.');